### ISSUE TITLE
Clientes

### ISSUE THREAD

**Issue by leoalmeidasa** [DevTechBrazil/pedido_certo_backend#1]

**Comment by leoalmeidasa** [comment]
- Cadastrar
  - [x] Adicionar Nome, Dados Pessoais
- Alterar
  - [x]  Alterar Nome, Dados Pessoais
- Deletar
  - [x]  Deletar Registro Especifico
- Listar
  - [x]  Listar todos os registros: ID, Descrição, Código Interno, timestamps
- Detalhar
  - [x]  Adicionar ID, Descrição, Código Interno, timestamps
